<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Salad_Monitoring_System___Server</RootNamespace>
    <UserSecretsId>aacefe69-8d0a-4381-9233-0edb12c91a00</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Swashbuckle" Version="5.5.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.4" />
    <PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
  </ItemGroup>

</Project>
